// Copyright 2026 The Orbit Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "orbit_webstore_private_api_provider.h"

// Generated by //orbit/common/api:generated_api_json_strings -- the same
// bundle OrbitExtensionsAPIProvider uses, extended with webstore_private.json.
#include "orbit/common/api/generated_schemas.h"

// Generated by //orbit/common/api:webstore_private_api_features; lands in
// namespace extensions, not orbit, per the generator's fixed output.
#include "orbit/common/api/webstore_private_api_features.h"

namespace orbit {

OrbitWebstorePrivateAPIProvider::OrbitWebstorePrivateAPIProvider() = default;
OrbitWebstorePrivateAPIProvider::~OrbitWebstorePrivateAPIProvider() = default;

void OrbitWebstorePrivateAPIProvider::AddAPIFeatures(
    extensions::FeatureProvider* provider) {
  extensions::AddOrbitWebstorePrivateAPIFeatures(provider);
}

void OrbitWebstorePrivateAPIProvider::AddManifestFeatures(
    extensions::FeatureProvider* provider) {
  // webstorePrivate adds no manifest.json keys -- it is never available to
  // an installed extension, only to the store's own web page context.
}

void OrbitWebstorePrivateAPIProvider::AddPermissionFeatures(
    extensions::FeatureProvider* provider) {
  // Reachability is entirely origin-gated (see _webstore_private_api_features
  // .json); there is no "webstorePrivate" manifest permission to declare.
}

void OrbitWebstorePrivateAPIProvider::AddBehaviorFeatures(
    extensions::FeatureProvider* provider) {}

void OrbitWebstorePrivateAPIProvider::AddAPIJSONSources(
    extensions::JSONFeatureProviderSource* json_source) {
  // Only consumed by chrome.test's feature-introspection helpers, which
  // Orbit does not ship.
}

bool OrbitWebstorePrivateAPIProvider::IsAPISchemaGenerated(
    const std::string& name) {
  return api::OrbitGeneratedSchemas::IsGenerated(name);
}

std::string_view OrbitWebstorePrivateAPIProvider::GetAPISchema(
    const std::string& name) {
  return api::OrbitGeneratedSchemas::Get(name);
}

void OrbitWebstorePrivateAPIProvider::RegisterPermissions(
    extensions::PermissionsInfo* permissions_info) {}

void OrbitWebstorePrivateAPIProvider::RegisterManifestHandlers(
    extensions::ManifestHandlerRegistry* registry) {}

}  // namespace orbit
