// Copyright 2026 The Orbit Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "orbit_extensions_api_provider.h"

#include "extensions/common/alias.h"
#include "extensions/common/features/feature_provider.h"
#include "extensions/common/mojom/api_permission_id.mojom-shared.h"
#include "extensions/common/permissions/api_permission.h"
#include "extensions/common/permissions/permissions_info.h"

// Generated by //orbit/common/api:generated_api_json_strings.
#include "orbit/common/api/generated_schemas.h"

// Generated by //orbit/common/api:api_features/permission_features; both
// land in namespace extensions, not orbit, per the generator's fixed output.
#include "orbit/common/api/api_features.h"
#include "orbit/common/api/permission_features.h"

namespace orbit {

namespace {

using extensions::mojom::APIPermissionID;

// "tabs" is a chrome-layer permission CoreExtensionsAPIProvider never
// registers (//extensions has no chrome.tabs implementation); only the
// name<->id registration was missing here.
constexpr extensions::APIPermissionInfo::InitInfo kOrbitPermissionsToRegister[] = {
    {APIPermissionID::kTab, "tabs",
     extensions::APIPermissionInfo::kFlagRequiresManagementUIWarning},
    {APIPermissionID::kWebNavigation, "webNavigation",
     extensions::APIPermissionInfo::kFlagRequiresManagementUIWarning},
    // "cookies"/"privacy" are likewise chrome-layer permissions
    // CoreExtensionsAPIProvider never registers; only the name<->id
    // registration was missing.
    {APIPermissionID::kCookie, "cookies", 0},
    {APIPermissionID::kPrivacy, "privacy", 0},
    // chrome.scripting/chrome.management are implemented in //extensions
    // core, but their name<->id registration lives only in
    // chrome_api_permissions.cc; without these rows the manifest permission
    // is dropped as unknown and the dependency never resolves.
    {APIPermissionID::kScripting, "scripting",
     extensions::APIPermissionInfo::kFlagRequiresManagementUIWarning},
    {APIPermissionID::kManagement, "management", 0},
};

// chrome.windows has always been implemented by the same code as chrome.tabs
// and requests the same "tabs" permission under the alias "windows" --
// mirrors chrome_api_permissions.cc's own Alias("windows", "tabs").
constexpr extensions::Alias kOrbitPermissionAliases[] = {
    extensions::Alias("windows", "tabs"),
};

}  // namespace

OrbitExtensionsAPIProvider::OrbitExtensionsAPIProvider() = default;
OrbitExtensionsAPIProvider::~OrbitExtensionsAPIProvider() = default;

void OrbitExtensionsAPIProvider::AddAPIFeatures(
    extensions::FeatureProvider* provider) {
  extensions::AddOrbitAPIFeatures(provider);
}

void OrbitExtensionsAPIProvider::AddManifestFeatures(
    extensions::FeatureProvider* provider) {
  // No Orbit-specific manifest keys -- tabs/windows add no top-level
  // manifest.json entries, unlike e.g. "background" or "content_scripts".
}

void OrbitExtensionsAPIProvider::AddPermissionFeatures(
    extensions::FeatureProvider* provider) {
  extensions::AddOrbitPermissionFeatures(provider);
}

void OrbitExtensionsAPIProvider::AddBehaviorFeatures(
    extensions::FeatureProvider* provider) {}

void OrbitExtensionsAPIProvider::AddAPIJSONSources(
    extensions::JSONFeatureProviderSource* json_source) {
  // Unlike CoreExtensionsAPIProvider, Orbit's tabs.json/windows.json declare
  // no additional inline feature blocks beyond what _api_features.json
  // already states, so there is nothing extra to fold in here.
}

bool OrbitExtensionsAPIProvider::IsAPISchemaGenerated(
    const std::string& name) {
  // Named after generated_json_strings' bundle_name ("Orbit"), not the
  // generic "GeneratedSchemas".
  return api::OrbitGeneratedSchemas::IsGenerated(name);
}

std::string_view OrbitExtensionsAPIProvider::GetAPISchema(
    const std::string& name) {
  return api::OrbitGeneratedSchemas::Get(name);
}

void OrbitExtensionsAPIProvider::RegisterPermissions(
    extensions::PermissionsInfo* permissions_info) {
  permissions_info->RegisterPermissions(kOrbitPermissionsToRegister,
                                        kOrbitPermissionAliases);
}

void OrbitExtensionsAPIProvider::RegisterManifestHandlers(
    extensions::ManifestHandlerRegistry* registry) {}

}  // namespace orbit
